package CF.Metrics;

public class Constant {

	public static enum MetricEnum{
		GINI_INDEX,
		PEARSON_CORRELATION,
		PQ_MEAN,
		NORMALIZED_PROPORTION_OF_COMMOM_RATINGS, 
		NORMALIZED_PROPORTION_OF_RATINGS, 
		PROPORTION_OF_COMMOM_RATINGS, 
		PROPORTION_OF_RATINGS,
		STANDARD_DEVIATION,
		LOG_OF_QTD_RATINGS,
		LOG_OF_DATE_RATINGS,
		PR_OF_DATE_RATINGS,
		RATINGS_MEAN, LOGSDEVDATE,
	}
	
	public static enum VersionElementMetricEnum{
		ITEM_VALUE,
		USER_VALUE,
		ITEM_USER_VALUE;
	}
	
	public static enum VersionMetricEnum{
		ITEM_VALUE_FOR_ALL,
		USER_VALUE_FOR_ALL,
		ITEM_USER_VALUE_FOR_ALL_WITH_RATINGS;
	}
}
